## BASIC FUNCTIONS


In [1]:
import numpy as np
array1 = np.array([1,2,3,4])
print(array1)
print(type(array1))



[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
array2 = np.array([[1,2,3,4],[5,6.5,7,8],[9,10,11,12]])
print(array2)
print(array2.shape)
array2.dtype

[[ 1.   2.   3.   4. ]
 [ 5.   6.5  7.   8. ]
 [ 9.  10.  11.  12. ]]
(3, 4)


dtype('float64')

In [3]:
array2 = np.array([[1,2,3,4],[5,6.0,7,8],[9,10,11,12]],dtype='int32') #u can force also like here i did it
print(array2)
print(array2.shape)
array2.dtype

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


dtype('int32')

In [4]:
np.zeros((4,6)) # u to give the args in tuple when more than one dimension

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((4,6)) 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
np.ones((4,6),dtype="int32")


array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [7]:
np.empty((4,6)) # this values can be zero or 1 or garbage

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
array1*array1

array([ 1,  4,  9, 16])

In [9]:
array1**array1

array([  1,   4,  27, 256], dtype=int32)

In [10]:
array1/array1

array([1., 1., 1., 1.])

In [11]:
array2*array2 # it actually multiply elemnet by element of that row and col not the conventional way.


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

# Slicing

In [12]:
arr1 = np.array([55,66,77,88,99])
print(arr1[0])
print(arr1[1])
print(arr1[2])
print(arr1[3])
print(arr1[4])
print(arr1[0:5])
print(arr1[1:3])

arr3 = arr1[1:3]
print("I am arr3 ", arr3)
arr3[0] = 67
print("Changearr3[0] arr3 ", arr3)
print(arr1)

55
66
77
88
99
[55 66 77 88 99]
[66 77]
I am arr3  [66 77]
Changearr3[0] arr3  [67 77]
[55 67 77 88 99]


 # using copy() we can solve this issue

In [13]:
arr1 = np.array([55,66,77,88,99])
arr3 = arr1[1:3].copy()
print(arr3)
arr3[0] = 67
print(arr3)
print(arr1)

[66 77]
[67 77]
[55 66 77 88 99]


In [24]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr4[0])
print(arr4[1])
print(arr4[0][0])
print(arr4[0][3])
print(arr4[1,3])



[1 2 3 4]
[5 6 7 8]
1
4
8
