In [4]:
import numpy as np
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [26]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,55,6,4,7,8,5,5,8,5,-8,8,84,2000,5,6,1,5,5,6])
print(arr1.shape)
print(arr1.ndim)
arr1 = arr1.reshape(4,8)
arr1
arr1 = arr1.reshape(8,4)
arr1

(32,)
1


array([[   1,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12],
       [  13,   55,    6,    4],
       [   7,    8,    5,    5],
       [   8,    5,   -8,    8],
       [  84, 2000,    5,    6],
       [   1,    5,    5,    6]])

In [28]:
arr1.min()

-8

In [27]:
arr1.max()

2000

In [31]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,55,6,4,7,8,5,5,8,5,-8,8,84,2000,5,6,1,5,5,6])
np.argsort(arr1) # it gives the index to which u have to sort.

array([22,  0, 28,  1,  2, 15,  3, 18, 29, 26,  4, 21, 19, 30, 27,  5, 31,
       14, 16,  6, 17, 20, 23,  7,  8,  9, 10, 11, 12, 13, 24, 25],
      dtype=int32)

In [32]:
np.sort(arr1)

array([  -8,    1,    1,    2,    3,    4,    4,    5,    5,    5,    5,
          5,    5,    5,    6,    6,    6,    6,    7,    7,    8,    8,
          8,    8,    9,   10,   11,   12,   13,   55,   84, 2000])

In [43]:
arr1 = np.array([61,10,21,552,0,6])
np.argmin(arr1)

4

In [44]:
arr1 = np.array([61,10,21,552,0,6])
np.argmax(arr1)

3